confirm_os_window_close -1
enable_audio_bell no

shell_integration enabled
scrollback_lines 10000
remember_window_size yes

font_family FiraCode Nerd Font Mono
font_size 12.0

cursor_shape beam
cursor_blink_interval 0

window_padding_width 5
background_opacity 0.89

tab_bar_style powerline
tab_powerline_style angled

enabled_layouts vertical,horizontal,tall:bias=70;full_size=1;mirrored=false

mouse_map b5 press grabbed,ungrabbed copy_to_clipboard
mouse_map b4 press grabbed,ungrabbed paste_from_clipboard

map f1 launch --cwd=current
map f2 launch --type=tab --cwd=current
map f3 launch --type=tab --cwd=current nvim

include ~/.config/kitty/Catppuccin-Mocha.conf


# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME